### ISSUE TITLE
Where are the test cases and test steps? URGENT!!!!

### ISSUE THREAD

**Issue by RikiMerrick** [Jungyubw/newTCAMT#138]
was going to work on more test step data validation declarations, but I seem to not be able to get past the fist level of GU and NG.
Where are the test cases and related test steps?
It does list the last commit step with the proper date for LRI for my last changes.
![capture](https://cloud.githubusercontent.com/assets/22180804/23089122/1593969a-f539-11e6-9ffc-54b051e8cde8.JPG)

**Comment by Jungyubw** [comment]
Hello Riki,

First, I'm sorry to surprise you.
We changed the model, but we did not modify your TestPlan so it seemed to be missing from the tool. I have just checked the data in the DB and confirmed that all the data is safe.
(Just note that your last update date is 2/10.)
Monday is a holiday, so I will fix your Test Plan data on Tuesday morning so that you can use it without any problems.

Please let me know if you need work during this weekend. If necessary, I will try.

I am once again sorry for this.

**Comment by RikiMerrick** [comment]
No problem, good to hear that all is there.
Enjoy the long weekend!
